//
// Created by Paul McGinley on 30/09/2024.
//

#ifndef ANITYPE_H
#define ANITYPE_H

enum class AnimationType {
        ANIMATION_CONSUME,
        ANIMATION_DAMAGED,
        ANIMATION_DEATH,
        ANIMATION_DIZZY,
        ANIMATION_FIRE,
        ANIMATION_IDLE,
        ANIMATION_IDLE2,
        ANIMATION_INTERACT,
        ANIMATION_JUMP_AIR,
        ANIMATION_JUMP_END,
        ANIMATION_JUMP_START,
        ANIMATION_JUMP_UP,
        ANIMATION_PICKUP,
        ANIMATION_RUN,
        ANIMATION_WALK,
        ANIMATION_FLOAT_LEFT,
        ANIMATION_FLOAT_RIGHT,
        ANIMATION_TAUNT,
        ANIMATION_BATTLE_IDLE,
        ANIMATION_SENSE_SOMETHING_START,
        ANIMATION_SENSE_SOMETHING,
        ANIMATION_VICTORY,
        ANIMATION_DEAD,
        ANIMATION_ATTACK,
        ANIMATION_ATTACK2,
        ANIMATION_ATTACK2_START,
        ANIMATION_ATTACK2_REPEAT,
        ANIMATION_ATTACK3,
        ANIMATION_PROJECTILE_LEFT,
        ANIMATION_PROJECTILE_RIGHT,
        ANIMATION_EXPLOSION,
        ANIMATION_STATIC,
        ANIMATION_BRONZE_COIN,
        ANIMATION_SILVER_COIN,
        ANIMATION_GOLD_COIN,
        ANIMATION_GOLD_STAR_COIN,
        ANIMATION_BLUE_STAR_COIN,
};

#endif //ANITYPE_H
