//
// Created by Paul McGinley on 30/09/2024.
//

#ifndef FACEDIRECTION_H
#define FACEDIRECTION_H

enum FaceDirection {
    FACE_DIRECTION_LEFT = 0,
    FACE_DIRECTION_RIGHT_CHESTMONSTER = 199,
    FACE_DIRECTION_RIGHT_GENERIC = 275
};

#endif //FACEDIRECTION_H
